version: 2
jobs:
  test_regression_model:
    working_directory: ~/project
    docker:
      - image: circleci/python:3.10
    #!/usr/bin/env bash

steps:
  - checkout
  - run:
      name: Configure Kaggle credentials
      command: |
        mkdir -p ~/.kaggle
        echo '{"username":"${KAGGLE_USERNAME}","key":"${KAGGLE_KEY}"}' > ~/.kaggle/kaggle.json
        chmod 600 ~/.kaggle/kaggle.json
  - run:
      name: Running tests
      command: |
        virtualenv venv
        . venv/bin/activate
        pip install --upgrade pip
        pip install -r packages/regression_model/requirements.txt
        chmod +x ./scripts/fetch_kaggle_dataset.sh
        ./scripts/fetch_kaggle_dataset.sh
        py.test -vv packages/regression_model/tests

workflows:
  version: 2
  test-all:
    jobs:
      - test_regression_model
